### ISSUE TITLE
How to use this Library

### ISSUE THREAD

**Issue by Serobegi** [espressif/esp-idf-provisioning-android#13]
Hello.

i'm now Include library & define "private ESPProvisionManager espProvisionManager; "

but, I don't understand why Scan QRCODE?" 
 
& What is "TransportType transportType", "SecurityType securityType" ?

Please let me know if there is an easy example of using the library.

**Comment by khushbushah2302** [comment]
@Serobegi ,

This library is useful for doing WiFi provisioning of ESP32 / ESP32-S2 devices. 
There are two types of transports are supported to communicate with the device - BLE and SoftAP. 
So according to transport of a device, set TransportType - TRANSPORT_BLE and TRANSPORT_SOFTAP.
2 security types are available - Security0 and Security1.
So according to security of a device, set SecurityType to - SECURITY_0 and SECURITY_1.

[This app](https://github.com/espressif/esp-idf-provisioning-android) is itself an example of using the library.

QR code is useful to connect with device using device information from QR code. QR code data will give device information as below, 
```
 {"ver":"v1","name":"PROV_000318","pop":"a1000318","transport":"softap"}
 {"ver":"v1","name":"PROV_EB15D5","pop":"abcd1234","transport":"ble"}
```
To call scanQRCode API, app needs to pass SurfaceView to lib to display camera.

If you don't have QR code, then you can also connect device manually.

**Comment by Serobegi** [comment]
Hi!
I really waited for you.
I hope you can see my code for a moment.
```
                espDevice = ESPProvisionManager.getInstance(getApplicationContext()).createESPDevice(TransportType.TRANSPORT_BLE, ESPConstants.SecurityType.SECURITY_0);
                ESPProvisionManager.getInstance(getApplicationContext()).searchBleEspDevices(bleScanListener);

                BluetoothDevice clickBluetoothDevice = bluetoothAdapter.getRemoteDevice(detailInfo[2]);
                espDevice.connectBLEDevice(clickBluetoothDevice, String.valueOf(detailInfo[1]));
                clickBluetoothDevice.createBond();
                espDevice.connectWiFiDevice();
                espDevice.scanNetworks(wifiScanListener);
                espDevice.provision(ssid, passphrase, provisionListener);

```
Is pairing required for esp32 provisioning?

"ClickBluetoothDevice.createBond();" in the code If you don't put this in, you won't be able to connect to esp32.

Also, how did I create "bleScanListener", but I don't know how to restructure the "wifiScanListener" and "provisionListener".

**Comment by khushbushah2302** [comment]
Hi @Serobegi ,

After calling `searchBleEspDevices` API, app will receive `BluetoothDevice` in `onPeripheralFound` callback of `bleScanListener`.
After receiving `BluetoothDevice`, app needs to call `espDevice.connectBLEDevice(device, primaryServiceUuid);`

```
String serviceUuid = "";

@Override
public void onPeripheralFound(BluetoothDevice device, ScanResult scanResult) {

    Log.d(TAG, "====== onPeripheralFound ===== " + device.getName());
    if (scanResult.getScanRecord().getServiceUuids() != null && scanResult.getScanRecord().getServiceUuids().size() > 0) {
        serviceUuid = scanResult.getScanRecord().getServiceUuids().get(0).toString();
    }
}
```

App does not need to call createBond(). 
And in above code, these is line - `espDevice.connectWiFiDevice();' 
This API call is not require for BLE transport device. It is for SoftAP device.

After calling this `espDevice.connectBLEDevice(device, primaryServiceUuid)` , app will receive event of device connected.

Refer [this file](https://github.com/espressif/esp-idf-provisioning-android/blob/403c787f32cd8f0837d9a0b92624d51ce0e1d29f/app/src/main/java/com/espressif/ui/activities/BLEProvisionLanding.java#L212) for your reference

**Comment by khushbushah2302** [comment]
WifiScanListener and ProvisionListener are implemented in [WiFiScanList](https://github.com/espressif/esp-idf-provisioning-android/blob/master/app/src/main/java/com/espressif/ui/activities/WiFiScanActivity.java) and [ProvisioningActivity](https://github.com/espressif/esp-idf-provisioning-android/blob/master/app/src/main/java/com/espressif/ui/activities/ProvisionActivity.java) files.

**Comment by khushbushah2302** [comment]
Hi @Serobegi ,

Updated README for the use of provisioning library.
Let us know if you face any issue or any doubt for the library.

Thanks.
