### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by Tingdang** [espressif/esp-idf-provisioning-android#17]
I download the latest projest and Build with Android Studio,but error happened:
Some problems were found with the configuration of task ':app:generateBleSec0AvsDebugProto'.
> Directory 'D:\Android\AndroidAPP\ESP_Alexa\app\build\extracted-include-protos\avs' specified for property '$6' does not exist.
> Directory 'D:\Android\AndroidAPP\ESP_Alexa\app\build\extracted-include-protos\ble' specified for property '$12' does not exist.
> Directory 'D:\Android\AndroidAPP\ESP_Alexa\app\build\extracted-include-protos\bleSec0Avs' specified for property '$15' does not exist.
> Directory 'D:\Android\AndroidAPP\ESP_Alexa\app\build\extracted-include-protos\main' specified for property '$3' does not exist.
> Directory 'D:\Android\AndroidAPP\ESP_Alexa\app\build\extracted-include-protos\sec0' specified for property '$9' does not exist.

Help me, please!

**Comment by khushbushah2302** [comment]
Hi @Tingdang ,
What is your Android Studio version ?

**Comment by khushbushah2302** [comment]
Hi @Tingdang ,
May I know your Android Studio version ?

**Comment by Tingdang** [comment]
I found the reason myself: you can't update gradle and gradle plugin, must be same as the origin, or you will build failed!
