### ISSUE TITLE
Getting the BSSID in softAP

### ISSUE THREAD

**Issue by gearsmotion789** [espressif/esp-idf-provisioning-android#18]
I wanted to know how it would be possible to retrieve the BSSID of the currently connected device in softAP mode. I know that the ESPTouch sample android app has this, but I haven't found any way to do so in this Provisioning app. How can I do this?

**Comment by khushbushah2302** [comment]
Hi @gearsmotion789 ,

You can get BSSID of the currently connected network by using this function. 

```
private String getBSSID() {

        String bssid = null;
        WifiManager wifiManager = (WifiManager) getApplicationContext().getSystemService(Context.WIFI_SERVICE);
        WifiInfo wifiInfo = wifiManager.getConnectionInfo();
        if (wifiInfo.getSupplicantState() == SupplicantState.COMPLETED) {

            bssid = wifiInfo.getBSSID();
        }
        return bssid;
    }
```

**Comment by gearsmotion789** [comment]
@khushbushah2302 Thank you very much. It works.

**Comment by shahpiyushv** [comment]
Closing this issue as it has been resolved.
