### ISSUE TITLE
Running with a custom Product ID

### ISSUE THREAD

**Issue by klisevich** [espressif/esp-idf-provisioning-android#19]
Hi!
I struggling to run provisioning with a custom AWS account and AVS product id. As I'm not an experienced Android developer, so could you kindly provide example files with changes(what and where) that I should make in the Android project to run with a custom product id.

**Comment by khushbushah2302** [comment]
Hi @klisevich , 
I will update ReadMe to do changes in Android source code.

**Comment by klisevich** [comment]
> Hi @klisevich ,
> I will update ReadMe to do changes in Android source code.

Thanks, looking forward to it!

**Comment by khushbushah2302** [comment]
HI @klisevich ,

Updated steps in ReadMe. Let me know if you face any difficulty for custom product id.
