### ISSUE TITLE
import espressif.Sec0; not working in Android Studio

### ISSUE THREAD

**Issue by naderahmed** [espressif/esp-idf-provisioning-android#2]
I downloaded release 1_0_1 and imported it into Android Studio, and now I am getting many errors:

It can not resolve this:
import espressif.Sec0;

I found Sec0 in the following directory:

/Users/nader/Documents/esp32_android/esp-idf-provisioning-android-release_1_0_1/app/src/main/proto

but for some reason, Android Studio is not able to find it. 

![screen shot 2018-12-13 at 8 42 18 am](https://user-images.githubusercontent.com/8256647/49942353-133a7780-feb3-11e8-8ced-88217c093f91.png)

**Comment by anujdeshpande** [comment]
@naderahmed - Can you please share the logs of your build command?

**Comment by 6vedant** [comment]
@anujdeshpande Same Problem here. Unable to get these classes: 

import espressif.Sec1;
import espressif.Session;

Provide the source code for the above classes.

**Comment by khushbushah2302** [comment]
@6vedant , Session and Sec1 are autogenerate classes from proto files.

Have you used same gradle files as in source code? 

Project gradle file should have below classpath.
'com.google.protobuf:protobuf-gradle-plugin:0.8.6'

And App level gradle file should have dependency for protobuf
 'com.google.protobuf:protobuf-lite:3.0.1'

**Comment by 6vedant** [comment]
@khushbushah2302  Thanks. It worked like charm.
