### ISSUE TITLE
No matching client found for package name

### ISSUE THREAD

**Issue by klisevich** [espressif/esp-idf-provisioning-android#20]
Hi!
I followed README instruction to build a custom app. When building got an error:
```
No matching client found for package name 'com.klika.provision'
```
When I set `applicationId` back to `com.espressif.provbleavs` it works.
Should package name and `applicationId` be the same?

**Comment by khushbushah2302** [comment]
Hi @klisevich ,
We are looking into this issue and will update you soon.

**Comment by khushbushah2302** [comment]
Hi @klisevich ,
We have fixed the issue. Please take update and try with your applicationId` 'com.klika.provision'`.

**Comment by khushbushah2302** [comment]
Hi @klisevich ,
Does this update resolved `No matching client found for package name` issue ?

**Comment by klisevich** [comment]
> Hi @klisevich ,
> Does this update resolved `No matching client found for package name` issue ?
Sorry, i wasn`t able to check because we switched to code-based linking to work around the Android app issue.

**Comment by shahpiyushv** [comment]
Closing this issue as it has been fixed.
