### ISSUE TITLE
Problem during Alexa Authentication

### ISSUE THREAD

**Issue by Nicolo-sudo** [espressif/esp-idf-provisioning-android#21]
Hi,

First of all, thank you for your amazing work.
I'm experiencing a strange issue during the login phase.

What the problem is:
I cannot authenticate an user with Amazon Alexa Login becase once inserted credentials I receive "500 internal server error". The webpage doesn't close itself automatically and then the provisioning process can't complete so I dindn't receive any kind of callback like onSuccess, onError or onCancel.

What I have done:
- I cloned the repo
- I registered my application to the Amazon Developer Console
- I configured the Security Profile and configured the Alexa Voice Settings
- I created an Amazon Api Key wich I have put in the "api_key.txt" file
- I built and run the app

So, the LWA sdk is working fine and the Amazon Api Key is working, the login page is correctly shown to the user but unfortunately the authenticatuon process never complets because receive an 500 internal server error.

In your Readme.me file I saw that a "clientId" property should be declared under the Build Types settings. How can I set that field? Can you please share to me the code?
By using the LWA sdk, the clientId is necessary to get the Authorization?

The Amazon Login page once introduced the user credentials asks to allow the Amazon Alexa project. In your app version published on the Play Store the Amazon login page asks to allow at the esp_avs_open. Why there are two different scenarios? I’m missing some web or client configurations?

What about the error during the authentication phase? 
How can I solve that issue?

Thank you in advance.

**Comment by khushbushah2302** [comment]
Hi @Nicolo-sudo ,

There is no need to declare clientId in build type settings. Client id will be received from Amazon once login is successful.

LWA sdk first ask for Amazon login and after that it will ask for allowing for your product (for example it is asking for "esp_avs_open" product).
After doing login and allowing product, app will get success callback with `AuthorizeResult`. This result object contains client id, Authorization code, Redirect URI etc. information.

Can you install Amazon Shopping app in Android mobile and try again for provisioning with Play Store app ?
There is some issue with doing login in browser. Working on it.

**Comment by Nicolo-sudo** [comment]
Thank you for the quick response, I got this working now.

The problem was that I was passing the wrong ProductID to Amazon Login Sdk.

Thank you!
