### ISSUE TITLE
Write to BLE failed

### ISSUE THREAD

**Issue by n-maiya** [espressif/esp-idf-provisioning-android#23]
I'm using the latest code from versions/avs-ble branch of this repo with head version of esp-va-sdk master.
I'm trying to provision using BLE. I see my device in the list but when I select the device it gets stuck.

The logs on Android app side: 

W/System.err: org.json.JSONException: Value SUCCESS of type java.lang.String cannot be converted to JSONObject (at BLETransportLatest.java:301)
java.lang.Exception: Write to BLE failed (at BLETransportLatest.java:377)

On the device side: 
W (30371) BT_APPL: BTA got unregistered event id 31
E (32291) security1: Security version mismatch. Closing connection
E (32291) protocomm_ble: Invalid content received, killing connection

On the Android side I am using bleSec1AvsDebug build variant. I tried bleSec0AvsDebug as well but I get the same error. 

Looks like a version mismatch. Any suggestion on how I can get it working quickly?

**Comment by n-maiya** [comment]
> I'm using the latest code from versions/avs-ble branch of this repo with head version of esp-va-sdk master.
> I'm trying to provision using BLE. I see my device in the list but when I select the device it gets stuck.
> 
> The logs on Android app side:
> 
> W/System.err: org.json.JSONException: Value SUCCESS of type java.lang.String cannot be converted to JSONObject (at BLETransportLatest.java:301)
> java.lang.Exception: Write to BLE failed (at BLETransportLatest.java:377)
> 
> On the device side:
> W (30371) BT_APPL: BTA got unregistered event id 31
> E (32291) security1: Security version mismatch. Closing connection
> E (32291) protocomm_ble: Invalid content received, killing connection
> 
> On the Android side I am using bleSec1AvsDebug build variant. I tried bleSec0AvsDebug as well but I get the same error.
> 
> Looks like a version mismatch. Any suggestion on how I can get it working quickly?

It was a build flavor mismatch on the Android side.

**Comment by shahpiyushv** [comment]
Closing this issue as it has been resolved.
