### ISSUE TITLE
Library never uses event type ESPConstants.EVENT_DEVICE_DISCONNECTED

### ISSUE THREAD

**Issue by devinbrown7** [espressif/esp-idf-provisioning-android#26]
I would expect the library to publish the event type `ESPConstants.EVENT_DEVICE_DISCONNECTED` some time after calling `ESPDevice.disconnectDevice()`. The only event type I am receiving after disconnecting is `ESPDevice.EVENT_DEVICE_CONNECTION_FAILED` which means I cannot discern between a connection failure and an expected disconnection.

**Comment by khushbushah2302** [comment]
Hi @devinbrown7 , 
Thanks for observing this. We will update it this in library.

**Comment by kyrylopiskovets** [comment]
Hello, this issue is still present in the latest version of the library.

**Comment by khushbushah2302** [comment]
Hi @devinbrown7 , @kyrylopiskovets ,

Fixed issue in new version of library (lib-2.0.7).
Thanks.
