### ISSUE TITLE
Selecting a device to provision and cancelling makes the devices disappear from the list

### ISSUE THREAD

**Issue by devinbrown7** [espressif/esp-idf-provisioning-android#27]
This is a behavior we found in the library version 2.0.5 while developing our app, and it is reproducible in the companion app. Calling `ESPDevice.disconnectDevice()` on a device leaves the actually hardware in a state where it stops advertising BLE for a while.

Steps to reproduce:
- Sample app in master
- Select "Provision New Device"
- Select "I don't have a QR code"
- Select "BLE"
- Select a device
- Wait for Proof of Possession screen
- Select "Cancel"
- Select "Provision New Device"
- Select "I don't have a QR code"
- Select "BLE"

Expected result:
- See all BLE devices

Actual result:
- See all BLE devices EXCEPT the one previously selected

**Comment by khushbushah2302** [comment]
@devinbrown7 ,

Apologies for the delayed response.
This issue is fixed in application. Thanks for reporting the issue.
