### ISSUE TITLE
How to use this application? 

### ISSUE THREAD

**Issue by zafersn** [espressif/esp-idf-provisioning-android#3]
How can I use this android application via wifi with softap_prov? What are the instructions for this?

**Comment by anujdeshpande** [comment]
Hi @zafersn 
You have to select the right build options from `Build Variant` view in Android Studio. There are multiple options that you can select, you can find information about them in the top level [Readme](https://github.com/espressif/esp-idf-provisioning-android#configuring-build).

If you want help in understanding the provisioning workflow, I recommend reading the official docs about provisioning [here](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/provisioning/provisioning.html).
