### ISSUE TITLE
Support Android SDK-21

### ISSUE THREAD

**Issue by JochemML** [espressif/esp-idf-provisioning-android#30]
Why is the minSdkVersion set to 23? I tried running the provisioning with a minSdkVersion set to 21 and everything seems to work.

**Comment by JochemML** [comment]
We are working on a react-native app that is using this library. Currently we use the same device-support as the popular package Expo(https://expo.io/). We want to support a minSdkVersion of 21. We tested this library with this version and everything seems to be working fine.

**Comment by khushbushah2302** [comment]
Hi @JochemML ,
Thanks for your contribution.
We will test library on Android SDK-21 and merge [this PR](https://github.com/espressif/esp-idf-provisioning-android/pull/31).

**Comment by JochemML** [comment]
Great, thank you for the quick response.

**Comment by khushbushah2302** [comment]
Hi @JochemML ,
We can close this issue as per [this reply](https://github.com/espressif/esp-idf-provisioning-android/pull/31#issuecomment-738753109) on PR.
Thanks.
