### ISSUE TITLE
scanNetoworks not works without set "ProofOfPossession"

### ISSUE THREAD

**Issue by developerGM** [espressif/esp-idf-provisioning-android#33]
I am creating the instance and the ESPDevice like this:

```
mProvisionManager = ESPProvisionManager.getInstance(requireContext());
mProvisionManager.createESPDevice(ESPConstants.TransportType.TRANSPORT_BLE, ESPConstants.SecurityType.SECURITY_1);
```

But to start with `scanNetowork` I need to `setProofOfPossession("")`
like this:

```
mProvisionManager.getEspDevice().setProofOfPossession("");
mProvisionManager.getEspDevice().scanNetworks()...
```

If I am not set as empty, the `scanNetowork` failed.

I see that should set pop otherwise the Security instance is null
`new Security1(proofOfPossession)`
end cannot create Session -> `new Session(transport, security)` 

So is it normal force to set `setProofOfPossession` as empty string?

**Comment by developerGM** [comment]
`ArrayList<String> deviceCaps = provisionManager.getEspDevice().getDeviceCapabilities();`

this array, in my case, contains 2 values: 'no_pop', 'wifi_scan'

so I need to replace the sample code with this

```
            case ESPConstants.EVENT_DEVICE_CONNECTED:
                Log.e(TAG, "Device Connected Event Received");
                ArrayList<String> deviceCaps = provisionManager.getEspDevice().getDeviceCapabilities();
                progressBar.setVisibility(View.GONE);
                isConnecting = false;
                isDeviceConnected = true;

                if (deviceCaps != null && !deviceCaps.contains("no_pop") && securityType == 1) {

                    goToPopActivity();

                } else if (deviceCaps.contains("wifi_scan")) {
                    
                    provisionManager.getEspDevice().setProofOfPossession("");
                    goToWifiScanListActivity();

                } else {

                    goToWiFiConfigActivity();
                }
                break;
```

**Comment by khushbushah2302** [comment]
@developerGM ,
In which class you need to change with above code ?

**Comment by developerGM** [comment]
There are 2 ways in my opinion:

1) Security1.java
```
    public Security1(String proofOfPossession) {
        --> if (TextUtils.isEmpty(proofOfPossession)) proofOfPossession = "";

        if(proofOfPossession != null) {
            this.proofOfPossession = proofOfPossession.getBytes();
        }
    }
```

or 

2) ESPDevice.java
```
private void initSession(final ResponseListener listener) {

        if (securityType.equals(ESPConstants.SecurityType.SECURITY_0)) {
            security = new Security0();
        } else {
        --> if (TextUtils.isEmpty(proofOfPossession)) proofOfPossession = "";

            security = new Security1(proofOfPossession);
        }
```

When use SECURITY_1, the var `proofOfPossession` should not `null`

**Comment by khushbushah2302** [comment]
Hi @developerGM ,

`proofOfPossession ` is already initialised by empty string in new version of library.
If you still need to do [this changes](https://github.com/espressif/esp-idf-provisioning-android/issues/33#issuecomment-748500763) with new app, then I would link to know in which class you need this change.

**Comment by developerGM** [comment]
Ok, I see now that there is a new version releases a few hours ago
` implementation 'com.github.espressif:esp-idf-provisioning-android:lib-2.0.7'`
So, I think that now this problem is solved. Thanks
