### ISSUE TITLE
Wil it Work for ESP 8266 

### ISSUE THREAD

**Issue by Ashwin-Sqt** [espressif/esp-idf-provisioning-android#34]
Will this app Work in ESP 8266 Wifi ... the think is that when i try to scan , it automatically scans for bluetooth device  .

**Comment by shahpiyushv** [comment]
@Ashwin-Sqt , if you use the SoftAP Provisioning in ESP8266, it will work with the ESP SoftAP Prov app.

**Comment by shahpiyushv** [comment]
Closing this issue as appropriate answer has been provided. Please feel free to reopen if required.
