### ISSUE TITLE
Protobuf Lite Issue

### ISSUE THREAD

**Issue by AliShehab93** [espressif/esp-idf-provisioning-android#37]
Dear, 

Crypto library needs to be updated to the last version. Also, protobuf Lite should be changed to use protobuf java Lite since protobuf lite makes duplicate classes when adding cloud firestore dependencies. Since firestore has updated their libraries from protobuf Lite to javaLite. And thus, I can't build my project with cloud firestore dependencies. So please if you may fix this in your package.

Best Regards,

**Comment by khushbushah2302** [comment]
@AliShehab93 ,
Thanks for reporting this issue. We will fix this asap.

**Comment by AliShehab93** [comment]
@khushbushah2302 Deal and thanks for your prompt response.
