### ISSUE TITLE
A questions about provising android app

### ISSUE THREAD

**Issue by JeonghunLee** [espressif/esp-idf-provisioning-android#38]
I am testing this app based on Android Studio in Window 10 so It's not working properly ,
Could you please tell me why reason is not working? 
I can't use jitpack (https://jitpack.io/)

**Comment by JeonghunLee** [comment]
I found how to use it :)

**Comment by shahpiyushv** [comment]
@JeonghunLee , would you mind sharing some info on what was the issue and how did you fix it, if you feel it could be useful for others? :)

**Comment by JeonghunLee** [comment]
I removed getGitHash related to getGitHash below and set build.gradle for module 

def getGitHash = { ->
    def stdout = new ByteArrayOutputStream()
    exec {
        commandLine 'git', 'rev-parse', '--short', 'HEAD'
        standardOutput = stdout
    }
    return stdout.toString().trim()
}

  https://github.com/espressif/esp-idf-provisioning-android/blob/master/app/build.gradle
