### ISSUE TITLE
softAp mode

### ISSUE THREAD

**Issue by xuanbach0805** [espressif/esp-idf-provisioning-android#4]
Dear
I compile and program on my Samsung. It's OK.
However, it only has ble mode, right? If not, please help me to enable SoftAP mode.

Regards,

**Comment by anujdeshpande** [comment]
Hi @xuanbach0805 - you can change the transport (BLE or softAP) and Security version (sec0 i.e. unencrypted or sec1) by changing the build variants in your Android Studio. If you are unable to see that particular view, you might have to enabled it from View->Tool Windows->Build Variants

**Comment by xuanbach0805** [comment]
Hi @anujdeshpande 
it runs softAp mode, however, I don't know what next step to do after connect SoftAp of device.
at least, it has to appear window to send out ssid and password of WiFi router to device.
This is some pictures on android app:
![IMG_9245](https://user-images.githubusercontent.com/6902832/56467574-e5f66b00-644a-11e9-90be-ce2505df304f.JPG)
![IMG_5117](https://user-images.githubusercontent.com/6902832/56467575-e5f66b00-644a-11e9-8e51-c7b0ddfab4ff.JPG)

And this is log of my device:

> I (13101) wifi: new:<1,0>, old:<1,0>, ap:<1,1>, sta:<255,255>, prof:1
> I (13101) wifi: station: 58:c5:cb:fd:51:83 join, AID=1, bgn, 20
> I (13101) hap_platform_wifi: Wi-Fi Event: 15
> W (13101) HAP Unified Prov: Unhandled event 15
> I (13111) hap_platform_wifi: A station connected to soft-AP
> I (13931) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2
> I (13931) hap_platform_wifi: Wi-Fi Event: 17
> W (13931) HAP Unified Prov: Unhandled event 17
> W (15141) httpd_uri: httpd_uri: URI '/' not found
> W (15141) httpd_txrx: httpd_resp_send_err: 404 Not Found - This URI does not exist

Thank you so much.

**Comment by anujdeshpande** [comment]
Once you have connected to the ssid you can come back to the app and provision the device. The app will see that it is connected to an esp32/8266 device and establish a protocomm session to it

**Comment by Saifu786** [comment]
Hello Sie/Mam,
I just need esp32 wifi provisioning with android and i stuck in that as they have Bluetooth also in that.

**Comment by Saifu786** [comment]
if am commenting Bluetooth part then am getting Cannot establish session.

**Comment by anujdeshpande** [comment]
@Saifu786 You have to pick the right variant from the build variants menu in Android Studio

**Comment by Saifu786** [comment]
Actually I have commented Bluetooth part from esp-idf but am getting issue
like Cannot establish session.And in softAp am getting response also null.

**Comment by kangbudz** [comment]
@Saifu786 i guess default provisioning mode is WiFiSec1. So build variant in android studio should be select to WiFiSec1Debug or Release.

**Comment by khushbushah2302** [comment]
Hi @xuanbach0805 ,
Please check our latest app. App has both SoftAP and BLE mode in its Settings.

**Comment by shahpiyushv** [comment]
Closing this issue as it has been resolved.
