### ISSUE TITLE
ESP device didn't show up in app while scanning

### ISSUE THREAD

**Issue by obitodarky** [espressif/esp-idf-provisioning-android#41]
I ran this app and tried to scan for my ESP32 device using BLE Scan, in the app UI, nothing shows up but I get the following in my Android Studio Console: 
```
D/ESP:BleScanner: ========== Device Found : ESP32
D/ESP:BleScanner: ========== Device Found : ESP32
D/ESP:BleScanner: ========== Device Found : ESP32
D/ESP:BleScanner: ========== Device Found : ESP32
D/ESP:BleScanner: ========== Device Found : ESP32
D/ESP:BleScanner: ========== Device Found : ESP32
```

Screenshot from my android device:
![image](https://user-images.githubusercontent.com/21317964/108977454-8f918d80-76ae-11eb-9010-bae7a0317b63.png)

Not sure what's wrong. I found the following error in the logcat:
`2021-02-24 14:32:05.239 30204-30408/? E/QTagParser: Error reading from /proc/net/xt_qtaguid/stats. Please check if this file exists.`

**Comment by khushbushah2302** [comment]
Hi @obitodarky ,

From Android studio logs, device name is "ESP32" and this screen will display those devices whose names starts with "PROV_" prefix. 
Please click on "Change" and remove "PROV_" prefix value. 
You can also set your prefix value like "ESP".

**Comment by obitodarky** [comment]
Oh yes, of course. Thanks @khushbushah2302

The device did pop up in the list, I got this error when I tried to connect to it:
```
W/BluetoothGatt: Unhandled exception in callback
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at java.util.UUID.fromString(UUID.java:192)
        at com.espressif.provisioning.transport.BLETransport.readNextDescriptor(BLETransport.java:397)
        at com.espressif.provisioning.transport.BLETransport.access$400(BLETransport.java:49)
        at com.espressif.provisioning.transport.BLETransport$1.onDescriptorRead(BLETransport.java:252)
        at android.bluetooth.BluetoothGatt$1$9.run(BluetoothGatt.java:520)
        at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:770)
        at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:39)
        at android.bluetooth.BluetoothGatt$1.onDescriptorRead(BluetoothGatt.java:514)
        at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:161)
        at android.os.Binder.execTransact(Binder.java:731)
```

**Comment by khushbushah2302** [comment]
The above error shows, app is not able to find BluetoothGattCharacteristic for "proto-ver".
Can you give some detail about device firmware ? Which example are you using ?

**Comment by obitodarky** [comment]
I'm sorry, I'm kind of new to this. What details do you need about the firmware? 

I ran the BLE_server_multiconnect example...

**Comment by obitodarky** [comment]
Sorry to ping you @khushbushah2302 but can you help me out and tell me what I might be doing wrong?

**Comment by shahpiyushv** [comment]
@obitodarky , I think there may be some confusion. This repository is for the ESP Provisioning apps, the details for which you can find [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/provisioning/provisioning.html). It works with the [these esp-idf examples](https://github.com/espressif/esp-idf/tree/master/examples/provisioning). If you have been using Arduino, the corresponding example can be found [here](https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFiProv/examples/WiFiProv).
