### ISSUE TITLE
Getting the BSSID/MAC in BLE

### ISSUE THREAD

**Issue by tobyloki** [espressif/esp-idf-provisioning-android#44]
I wanted to know how it would be possible to retrieve the BSSID/MAC of the currently connected device in BLE mode. I've learned how to do it in softAP mode from https://github.com/espressif/esp-idf-provisioning-android/issues/18, but this approach wouldn't work for BLE. How can I do this? Thank you.

**Comment by khushbushah2302** [comment]
Hi @tobyloki ,

You can get hardware address of BLE device using `getAddress()` method `BluetoothDevice` instance.

**Comment by shahpiyushv** [comment]
Closing this issue since there hasn't been any response. Please feel to file new issue if required.
