### ISSUE TITLE
Espressif::Security1: Protocol message tag had invalid wire type.

### ISSUE THREAD

**Issue by dariobertini** [espressif/esp-idf-provisioning-android#46]
I'm able to successfully connect via BLE to device, but when I send the wifi configuration using the method provision, on console i see the following error:
E/Espressif::Security1: Protocol message tag had invalid wire type.

**Comment by khushbushah2302** [comment]
Hi @dariobertini ,

Is your device has Proof of possession ? If yes, need to set proof of possession value in application before sending wifi config or any data to device.

**Comment by dariobertini** [comment]
> Hi @dariobertini ,
> 
> Is your device has Proof of possession ? If yes, need to set proof of possession value in application before sending wifi config or any data to device.

hi @khushbushah2302 , thank you for your reply, unfortunately i'm already doing like this.
below my code:
`device.setProofOfPossession(pop);`
`device.provision(ssid, passphrase, new ProvisionListener() {....`

**Comment by dariobertini** [comment]
hi @khushbushah2302 ,

I get more information about the issue, the exact point where I get this error is on line 122 of Security1.java, in correspondence of the "copyFrom" 
`    private byte[] getStep1Request() {`    
        `    Sec1.SessionCmd1 sessionCmd1 = Sec1.SessionCmd1`    
              `      .newBuilder()`    
               `     .setClientVerifyData(ByteString.copyFrom(this.clientVerify))`    
              `      .build();`

**Comment by khushbushah2302** [comment]
Hi @dariobertini , 
Can you share how `device` instance is created  and then connected with device using BLE ?

**Comment by dariobertini** [comment]
> Hi @dariobertini ,
> Can you share how `device` instance is created and then connected with device using BLE ?

Hi @khushbushah2302 ,
we create the device with this code:
`ESPProvisionManager provisionManager = ESPProvisionManager.getInstance(this.getContext());`
`provisionManager.createESPDevice(ESPConstants.TransportType.TRANSPORT_BLE, ESPConstants.SecurityType.SECURITY_1);`

after we connect to BLE :
`provisionManager.getEspDevice().connectBLEDevice(bleDevice,uuid);`

ON ESPConstants.EVENT_DEVICE_CONNECTED event:
`this.provisionManager.getEspDevice().setProofOfPossession(pop);`
`this.provisionManager.getEspDevice().provision(ssid, passphrase, new ProvisionListener() {....`

**Comment by dariobertini** [comment]
Hi @khushbushah2302 ,

after days of investigation we found out the cause of this issue:
we was using Subscribe to event with POSTING instead of MAIN,
 WRONG:  `@Subscribe(threadMode = ThreadMode.POSTING)`
 RIGHT:   `@Subscribe(threadMode = ThreadMode.MAIN)`
 
 thank you for your support
