### ISSUE TITLE
Can someone give me an implementation example?

### ISSUE THREAD

**Issue by manbomb** [espressif/esp-idf-provisioning-android#49]
I'm trying to write a bridge between react native and android for this lib, I want to do this only for Android first. Can someone give me an simple done app that implements this lib? Just for help me. Thanks.

**Comment by shahpiyushv** [comment]
@manbomb , [this thread](https://github.com/espressif/esp-rainmaker/issues/9) may be of interest to you.

**Comment by manbomb** [comment]
> @manbomb , [this thread](https://github.com/espressif/esp-rainmaker/issues/9) may be of interest to you.

Thanks @shahpiyushv. But i still need a simple example of a native implementation, because i haven't find it in this thread.

**Comment by manbomb** [comment]
I'm trying to make a native app now. What is a "BleScanListener"?

`ESPProvisionManager.getInstance(context).searchBleEspDevices(String prefix, BleScanListener bleScannerListener)
`

My code now is like:

````
public class MainActivity extends AppCompatActivity implements View.OnClickListener {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button buttonFirst = findViewById(R.id.firstTestButton);
        buttonFirst.setOnClickListener(this);
    }

    @Override
    public void onClick(View v) {
        ESPProvisionManager.getInstance(this).searchBleEspDevices("prov_", );
        Toast.makeText(this, "Eu estou aqui, eu vou te ajudar. Deus", Toast.LENGTH_LONG).show();
    }
}
```

Can you help me @shahpiyushv ?

**Comment by khushbushah2302** [comment]
Hi @manbomb ,
`BleScanListener` is an interface for BLE device scanning. It will give different callbacks like scan completed, peripheral found (when BLE device will be found with given prefix) etc.
You can check in [this file](https://github.com/espressif/esp-idf-provisioning-android/blob/c954595ba2531a0c457496dd8058bdbbac2904e4/app/src/main/java/com/espressif/ui/activities/BLEProvisionLanding.java#L419).
This repo itself a provisioning app with library usage so you can check app code.

**Comment by manbomb** [comment]
Thanks @shahpiyushv and @khushbushah2302 , thanks very much
