### ISSUE TITLE
BLE provisioning under Android 11

### ISSUE THREAD

**Issue by samycharas** [espressif/esp-idf-provisioning-android#50]
I am working with an esp32-vroom mcu based board, and I've been provisioning it using both the ESP BLE Prov, and the ESP RainMaker which is working all great. I've recently upgraded my phone to the most recent Android OS, and under this os, provisioning becomes unreliable.
When selecting a device to pair with within the app, the wifi menu doesn't show up anymore, pairing action just hangs until the device is eventually disconnected, and the following error appears : 
![image](https://user-images.githubusercontent.com/62038402/121935485-c3b9b880-cd48-11eb-9ff3-7cd6954f4d6e.png)

error! communication failed. device may not be supported.
Resetting the network settings of the phone allows and relaunching the esp application "fixes" the issue as now, after selecting my device, I am prompted to pair the device by the following message: Do you want to pair with MY_DEVICE device? 
![image](https://user-images.githubusercontent.com/62038402/121935558-d92ee280-cd48-11eb-97d3-b844db952461.png)

The pairing here prompts the wifi menu and I am then able to provision my board.
I would like to know if anyone else has been meeting the same behavior with the new OS, knows what exactly causes this behavior, and has a better workaround than resetting network settings everytime?

Edit : Add pictures.

**Comment by khushbushah2302** [comment]
Hi @samycharas ,

I have tried BLE provisioning with Android 11. It is working at my side. 
 Unfortunately, I was not able to reproduce this issue.

Can you please remove/unpair device from phone's bluetooth settings (if device is there in bluetooth settings) and then try again ?

**Comment by samycharas** [comment]
Hi @khushbushah2302, we've narrowed down potential issues, and figured out it came from the esp-idf we were using in some case involving different behavior on the board for the same firmware. We have a stable version now, so I'll close this issue. Thanks for looking into it.
