### ISSUE TITLE
Support of i18n

### ISSUE THREAD

**Issue by leventesen** [espressif/esp-idf-provisioning-android#54]
Do you consider i18n feature for both android and ios provisioning apps?

If so I can translate to Turkish.

I'm asking this because we have a project and want to use these apps just with translating to Turkish but don't want to duplicate projects and push to stores also I'm not sure if it's ok to do this for you because of legal issues?

What is the best approach for this situation?

**Comment by khushbushah2302** [comment]
Hi @leventesen ,
The app supports localization. 
Create "values" folder for Turkish language (values-tr possibly) in [res](https://github.com/espressif/esp-idf-provisioning-android/tree/master/app/src/main/res) folder.
Translate strings of this file in Turkish (keep string names as they are) and add this translated strings.xml in your values folder.

**Comment by leventesen** [comment]
Thanks @khushbushah2302 for this information,

Will the app be published to official Espressif mobile account when I commit PR so every Turkish users can see this localized version?

**Comment by khushbushah2302** [comment]
Yes sure. You can send PR. We will merge it. 
Thanks for your efforts.

**Comment by shahpiyushv** [comment]
Closing this as there have been no further updates. It may be followed up later via a PR.
