### ISSUE TITLE
ESPDevice.connectBLEDevice not working on Android SDK <=24

### ISSUE THREAD

**Issue by markoImake** [espressif/esp-idf-provisioning-android#58]
When I try to connect to a device using connectBLEDevice after scanning, it fails to fire the connection callback. I checked the logs and found that during the service and characteristic discovery process I get this Gatt error status 5 for 'onCharacteristicWrite', which maps to GATT_INSUFFICIENT_AUTHENTICATION. 
I tested this on 3 seperate devices running Android 6 and 7.1 and they all have the same issue.

See logs below:

> 
> 2022-03-29 13:49:34.430 25252-25467/za.co.digitlab.GFConnect D/Espressif::BLETransport: onConnectionStateChange2, New state : 2, Status : 0
> 2022-03-29 13:49:34.431 25252-25467/za.co.digitlab.GFConnect E/Espressif::BLETransport: Connected to GATT server.
> 2022-03-29 13:49:34.463 25252-25264/za.co.digitlab.GFConnect D/Espressif::BLETransport: On services discovered
> 2022-03-29 13:49:34.463 25252-25264/za.co.digitlab.GFConnect D/Espressif::BLETransport: Characteristic UUID : 021aff50-0382-4aea-bff4-6b3f1c5adfb4
> 2022-03-29 13:49:34.463 25252-25264/za.co.digitlab.GFConnect D/Espressif::BLETransport: Characteristic UUID : 021aff51-0382-4aea-bff4-6b3f1c5adfb4
> 2022-03-29 13:49:34.463 25252-25264/za.co.digitlab.GFConnect D/Espressif::BLETransport: Characteristic UUID : 021aff52-0382-4aea-bff4-6b3f1c5adfb4
> 2022-03-29 13:49:34.463 25252-25264/za.co.digitlab.GFConnect D/Espressif::BLETransport: Characteristic UUID : 021aff53-0382-4aea-bff4-6b3f1c5adfb4
> 2022-03-29 13:49:34.463 25252-25264/za.co.digitlab.GFConnect D/Espressif::BLETransport: Characteristic UUID : 021aff54-0382-4aea-bff4-6b3f1c5adfb4
> 2022-03-29 13:49:34.464 25252-25264/za.co.digitlab.GFConnect D/Espressif::BLETransport: Descriptor : 00002901-0000-1000-8000-00805f9b34fb
> 2022-03-29 13:49:34.467 25252-25264/za.co.digitlab.GFConnect D/Espressif::BLETransport: Des read : true
> 2022-03-29 13:49:34.543 25252-25468/za.co.digitlab.GFConnect D/Espressif::BLETransport: DescriptorRead, : Status 0
> 2022-03-29 13:49:34.544 25252-25468/za.co.digitlab.GFConnect D/Espressif::BLETransport: DescriptorRead, Value : prov-scan for UUID : 021aff50-0382-4aea-bff4-6b3f1c5adfb4
> 2022-03-29 13:49:34.544 25252-25468/za.co.digitlab.GFConnect D/Espressif::BLETransport: Descriptor : 00002901-0000-1000-8000-00805f9b34fb
> 2022-03-29 13:49:34.546 25252-25468/za.co.digitlab.GFConnect D/Espressif::BLETransport: Des read : true
> 2022-03-29 13:49:34.640 25252-25467/za.co.digitlab.GFConnect D/Espressif::BLETransport: DescriptorRead, : Status 0
> 2022-03-29 13:49:34.640 25252-25467/za.co.digitlab.GFConnect D/Espressif::BLETransport: DescriptorRead, Value : prov-session for UUID : 021aff51-0382-4aea-bff4-6b3f1c5adfb4
> 2022-03-29 13:49:34.641 25252-25467/za.co.digitlab.GFConnect D/Espressif::BLETransport: Descriptor : 00002901-0000-1000-8000-00805f9b34fb
> 2022-03-29 13:49:34.643 25252-25467/za.co.digitlab.GFConnect D/Espressif::BLETransport: Des read : true
> 2022-03-29 13:49:34.738 25252-25468/za.co.digitlab.GFConnect D/Espressif::BLETransport: DescriptorRead, : Status 0
> 2022-03-29 13:49:34.738 25252-25468/za.co.digitlab.GFConnect D/Espressif::BLETransport: DescriptorRead, Value : prov-config for UUID : 021aff52-0382-4aea-bff4-6b3f1c5adfb4
> 2022-03-29 13:49:34.738 25252-25468/za.co.digitlab.GFConnect D/Espressif::BLETransport: Descriptor : 00002901-0000-1000-8000-00805f9b34fb
> 2022-03-29 13:49:34.739 25252-25468/za.co.digitlab.GFConnect D/Espressif::BLETransport: Des read : true
> 2022-03-29 13:49:34.836 25252-25265/za.co.digitlab.GFConnect D/Espressif::BLETransport: DescriptorRead, : Status 0
> 2022-03-29 13:49:34.836 25252-25265/za.co.digitlab.GFConnect D/Espressif::BLETransport: DescriptorRead, Value : proto-ver for UUID : 021aff53-0382-4aea-bff4-6b3f1c5adfb4
> 2022-03-29 13:49:34.837 25252-25265/za.co.digitlab.GFConnect D/Espressif::BLETransport: Descriptor : 00002901-0000-1000-8000-00805f9b34fb
> 2022-03-29 13:49:34.839 25252-25265/za.co.digitlab.GFConnect D/Espressif::BLETransport: Des read : true
> 2022-03-29 13:49:34.934 25252-25265/za.co.digitlab.GFConnect D/Espressif::BLETransport: DescriptorRead, : Status 0
> 2022-03-29 13:49:34.934 25252-25265/za.co.digitlab.GFConnect D/Espressif::BLETransport: DescriptorRead, Value : custom-data for UUID : 021aff54-0382-4aea-bff4-6b3f1c5adfb4
> 2022-03-29 13:49:35.031 25252-25265/za.co.digitlab.GFConnect D/Espressif::BLETransport: onCharacteristicWrite, status : 5
> 2022-03-29 13:49:35.031 25252-25265/za.co.digitlab.GFConnect D/Espressif::BLETransport: UUID : 021aff53-0382-4aea-bff4-6b3f1c5adfb4

**Comment by khushbushah2302** [comment]
Hi @markoImake ,

Please try disabling [CONFIG_WIFI_PROV_BLE_FORCE_ENCRYPTION](https://github.com/espressif/esp-idf/blob/01d014c42def8d0c19e1ce55c07de6761e092ffa/components/wifi_provisioning/Kconfig#L34), which you can find under Component Config -> Wi-Fi Provisioning Manager.

**Comment by khushbushah2302** [comment]
Hi @markoImake , have you tried after disabling [CONFIG_WIFI_PROV_BLE_FORCE_ENCRYPTION](https://github.com/espressif/esp-idf/blob/01d014c42def8d0c19e1ce55c07de6761e092ffa/components/wifi_provisioning/Kconfig#L34) flag.
You can also refer [this issue](https://github.com/espressif/esp-rainmaker-android/issues/25). It is similar.

**Comment by shahpiyushv** [comment]
Closing this since appropriate resolution has been provided.
