### ISSUE TITLE
Write to BLE failed error

### ISSUE THREAD

**Issue by kvbulusu** [espressif/esp-idf-provisioning-android#6]
After selecting the SSID and entering the password, It says "configurations applied", but at the end it says write to BLE failed. Didnt see this error before.  any suggestions what to look for or what can be done ?  I' using amazon-alexa from esp-va-sdk if it matters.

**Comment by anujdeshpande** [comment]
Hi @kvbulusu 
Can you share the device logs? From the board running the Alexa example

**Comment by kvbulusu** [comment]
@anujdeshpande  Here are the device logs snippet..please let me know if you have any further qns.

====
I (8) boot: ESP-IDF v3.2.2 2nd stage bootloader
I (8) boot: compile time 20:45:06
I (8) boot: Enabling RNG early entropy source...
I (12) boot: SPI Speed      : 80MHz
I (16) boot: SPI Mode       : DIO
I (20) boot: SPI Flash Size : 4MB
I (24) boot: Partition Table:
I (27) boot: ## Label            Usage          Type ST Offset   Length
I (35) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (42) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (50) boot:  2 factory          factory app      00 00 00010000 00390000
I (57) boot: End of partition table
I (61) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x1986bc (1672892) map
I (551) esp_image: segment 1: paddr=0x001a86e4 vaddr=0x3ffbdb60 size=0x0792c ( 31020) load
I (561) esp_image: segment 2: paddr=0x001b0018 vaddr=0x400d0018 size=0x1841fc (1589756) map
0x400d0018: _stext at ??:?

I (1018) esp_image: segment 3: paddr=0x0033421c vaddr=0x3ffc548c size=0x0092c (  2348) load
I (1019) esp_image: segment 4: paddr=0x00334b50 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at DBG/esp-idf/components/freertos/xtensa_vectors.S:1779

I (1025) esp_image: segment 5: paddr=0x00334f58 vaddr=0x40080400 size=0x1ad84 (109956) load
I (1070) esp_image: segment 6: paddr=0x0034fce4 vaddr=0x400c0000 size=0x0006c (   108) load
I (1070) esp_image: segment 7: paddr=0x0034fd58 vaddr=0x50000000 size=0x00060 (    96) load
I (1094) boot: Loaded app from partition at offset 0x10000
I (1094) boot: Disabling RNG early entropy source...
landscape width = 160 , height = 128 
W (1180) [SPIFFS]: No file system detected, formating...
W (4020) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration
[conn_mgr_prov]: Provisioning started with: 
	service name: ESP-Alexa-F6EC 
	service key: 
	proof of possession (pop): abcd1234
[alexa]: Waiting for time to be updated
[avs_config]: APP Got: ANoeJUVDQyAkseGFaHRX, amzn1.application-oa2-client.320d0c28204541e4a061b7aff8e7d1b9, amzn://com.espressif.provbleavs, abcd1234
[conn_mgr_prov]: Scan results:
    S.N. SSID                             RSSI
    [ 0] NTGR_VMB_1462061054               -40
    [ 1] Europa                            -42
    [ 2] LG_Smart_Refrigerator             -63
    [ 3] VINAM-2.4                         -75
    [ 4] SMISYSTEMS2                       -80
    [ 5] NTGR_VMB_1451459244               -83
    [ 6] ahsie                             -86
    [ 7] kitkat                            -90
    [ 8] eisha                             -91
[conn_mgr_prov_handler]: WiFi Credentials Received: 
	ssid: kitkat 
	password: kitkat
I (8) boot: ESP-IDF v3.2.2 2nd stage bootloader
I (8) boot: compile time 20:45:06
I (8) boot: Enabling RNG early entropy source...
I (12) boot: SPI Speed      : 80MHz
I (16) boot: SPI Mode       : DIO
I (20) boot: SPI Flash Size : 4MB
I (24) boot: Partition Table:
I (27) boot: ## Label            Usage          Type ST Offset   Length
I (35) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (42) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (50) boot:  2 factory          factory app      00 00 00010000 00390000
I (57) boot: End of partition table
I (61) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x1986bc (1672892) map
I (551) esp_image: segment 1: paddr=0x001a86e4 vaddr=0x3ffbdb60 size=0x0792c ( 31020) load
I (561) esp_image: segment 2: paddr=0x001b0018 vaddr=0x400d0018 size=0x1841fc (1589756) map
0x400d0018: _stext at ??:?

I (1018) esp_image: segment 3: paddr=0x0033421c vaddr=0x3ffc548c size=0x0092c (  2348) load
I (1019) esp_image: segment 4: paddr=0x00334b50 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at DBG/esp-idf/components/freertos/xtensa_vectors.S:1779

I (1025) esp_image: segment 5: paddr=0x00334f58 vaddr=0x40080400 size=0x1ad84 (109956) load
I (1070) esp_image: segment 6: paddr=0x0034fce4 vaddr=0x400c0000 size=0x0006c (   108) load
I (1070) esp_image: segment 7: paddr=0x0034fd58 vaddr=0x50000000 size=0x00060 (    96) load
I (1094) boot: Loaded app from partition at offset 0x10000
I (1094) boot: Disabling RNG early entropy source...
landscape width = 160 , height = 128 
[conn_mgr_prov]: Found ssid: kitkat
[conn_mgr_prov]: Found password: kitkat
W (2360) [app_main]: Already provisioned, Starting station

I (8) boot: ESP-IDF v3.2.2 2nd stage bootloader
I (8) boot: compile time 20:45:06
I (8) boot: Enabling RNG early entropy source...
I (12) boot: SPI Speed      : 80MHz
I (16) boot: SPI Mode       : DIO
I (20) boot: SPI Flash Size : 4MB
I (24) boot: Partition Table:
I (27) boot: ## Label            Usage          Type ST Offset   Length
I (35) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (42) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (50) boot:  2 factory          factory app      00 00 00010000 00390000
I (57) boot: End of partition table
I (61) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x1986bc (1672892) map
I (551) esp_image: segment 1: paddr=0x001a86e4 vaddr=0x3ffbdb60 size=0x0792c ( 31020) load
I (561) esp_image: segment 2: paddr=0x001b0018 vaddr=0x400d0018 size=0x1841fc (1589756) map
0x400d0018: _stext at ??:?

I (1018) esp_image: segment 3: paddr=0x0033421c vaddr=0x3ffc548c size=0x0092c (  2348) load
I (1019) esp_image: segment 4: paddr=0x00334b50 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at DBG/esp-idf/components/freertos/xtensa_vectors.S:1779

I (1025) esp_image: segment 5: paddr=0x00334f58 vaddr=0x40080400 size=0x1ad84 (109956) load
I (1070) esp_image: segment 6: paddr=0x0034fce4 vaddr=0x400c0000 size=0x0006c (   108) load
I (1070) esp_image: segment 7: paddr=0x0034fd58 vaddr=0x50000000 size=0x00060 (    96) load
I (1094) boot: Loaded app from partition at offset 0x10000
I (1094) boot: Disabling RNG early entropy source...
================

**Comment by khushbushah2302** [comment]
Hi @kvbulusu ,

Sorry for not getting back to you sooner.
Are you still facing this issue in current version of app ?

**Comment by shahpiyushv** [comment]
Closing this issue as there hasn't been much activity here. Please feel free to reopen of required.
