### ISSUE TITLE
Failed to resolve: com.github.espressif:esp-idf-provisioning-android:lib-2.0.13

### ISSUE THREAD

**Issue by Marcrobito** [espressif/esp-idf-provisioning-android#66]
I already added the maven { url 'https://jitpack.io' } to repositories but i cant resolve the dependency

**Comment by khushbushah2302** [comment]
We are using this lib in our ESP RainMaker project. [Here](https://github.com/espressif/esp-rainmaker-android/blob/5ecc246ac1cecc35e2f7ddfae446117f1377d85c/app/build.gradle#L189) is its dependency.
Can you share your project level build.gradle file ?

**Comment by Marcrobito** [comment]
buildscript {
    ext {
        compose_version = '1.3.0-alpha02'
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '7.2.1' apply false
    id 'com.android.library' version '7.2.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.5.31' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

///settings.gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

**Comment by Marcrobito** [comment]
solved
pluginManagement {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}
dependencyResolutionManagement {
    ...
    repositories {
        ....
        maven { url 'https://jitpack.io' }
    }
}

that was missed inside the settings.gradle
