### ISSUE TITLE
target API level 31

### ISSUE THREAD

**Issue by bbinet** [espressif/esp-idf-provisioning-android#75]
Starting in November 2022, app updates must target API level 31 or above and adjust for behavioral changes in Android 12.

See: https://developer.android.com/google/play/requirements/target-sdk

**Comment by bbinet** [comment]
[Rainmaker Android app has already upgraded its Android target SDK to version 31](https://github.com/espressif/esp-rainmaker-android/commit/49ae371c8c577475b473ecfd4f2aa191cfa4f6c3), it would be great if esp-idf-provisioning-android could do it to.

Do you plan to upgrade target SDK version anytime soon?

**Comment by khushbushah2302** [comment]
Hi @bbinet, Yes. Upgrading the target SDK is already in progress. It will be available within a month.

**Comment by bbinet** [comment]
Thank you @khushbushah2302

**Comment by rahulvageriya** [comment]
@khushbushah2302 is there any update with targetSDK version 31 . We upgrade our project with 31 target SDK version since it is mandatory for new app update. But after that scanBleDevices getting failed for Android 10 and Android 11 ? 
is there any update ?
