### ISSUE TITLE
I don't see the function for get IP address wifi in Android (Returns the wireless network IP 4 address)

### ISSUE THREAD

**Issue by LeKyDF** [espressif/esp-idf-provisioning-android#76]
In IOS ( https://github.com/espressif/esp-idf-provisioning-ios/blob/master/ESPProvision/ESPDevice.swift )
// Returns the wireless network IP 4 address after successful provision.
    public func wifiConnectedIp4Addr() -> String? {
        return self.provision?.wifiConnectedIp4Addr
    }

but I don't see in Android. Please help !!!

**Comment by LeKyDF** [comment]
please help me !!!

**Comment by khushbushah2302** [comment]
Hi @LeKyDF , 
[Here](https://github.com/espressif/esp-idf-provisioning-android/blob/798842c7f9372473604b8e01b763ac546d0c4d66/app/src/main/java/com/espressif/ui/activities/AddDeviceActivity.java#L704) is a method to take SSID. 
You can get IP address by calling `getIpAddress()` API on `WifiInfo` instance.

**Comment by LeKyDF** [comment]
I use WifiInfor but I see problem : WifiInfo!' is deprecated. Deprecated in Java . I am using android 12
