### ISSUE TITLE
SDK v3.3rc --> Provisioning failed to find device during scan 

### ISSUE THREAD

**Issue by kangbudz** [espressif/esp-idf-provisioning-android#8]
Give it try to update SDK into latest v3.3 release candidate version, but no luck with provisioning via BT. Scanning device is end with no device found , below is android debug log:
`D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=6
D/BluetoothAdapter: STATE_ON
V/RenderScript: 0x55c16f33a0 Launching thread(s), CPUs 8
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@da3614d
D/BluetoothAdapter: STATE_ON`

with previous sdk v3.2.2 , provisioning via BT is running well,BLE transport work well during scan:
`D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=6
D/Espressif::BLETransport: Got scan result
D/Espressif::BLETransport: Got scan result2
D/Espressif::BLETransport: Got scan result`

Is there anyone have similar issue?

**Comment by kangbudz** [comment]
i closes this issue. scan no result caused by uuid service is different . i used nrf connect and put correct uuid in android apps.

**Comment by khushbushah2302** [comment]
@kangbudz Current android app is not compatible with SDK v3.3. We will release Android app which will be compatible with SDK v3.3rc very soon.

**Comment by kangbudz** [comment]
thank you @khushbushah2302 ... currently i try change BT uuid and prov apps now able to get the device..
