### ISSUE TITLE
Jitpack Dependency Unavailable

### ISSUE THREAD

**Issue by aa-v** [espressif/esp-idf-provisioning-android#84]
I am unable to use the jitpack instructions as outlined. Always fails the resolve the package, while jitpack seems to be available. Using Gradle 7.* is there any possibility of publishing the package somewhere else, or releasing jars please?

FAILURE: Build failed with an exception.
```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.espressif:esp-idf-provisioning-android:lib-2.1.0.
```

This is the same with 2.1.1 2.1.2 despite the fact that I can see the successful builds in jitpack and I have  maven { url ("https://jitpack.io/") } in my build.gradle.

**Comment by khushbushah2302** [comment]
Hi @aa-v , thanks for reporting this issue. I will check and update you soon.

**Comment by aa-v** [comment]
Thank you @khushbushah2302 I am using Android Studio Electric Eel which is the latest stable

**Comment by aa-v** [comment]
@khushbushah2302 any news on this please, we are forced to ship an embedded Jar in our library that depends on this. Thank you.

**Comment by khushbushah2302** [comment]
Hi @aa-v , 
Actually I am able to build and run app with the same Android studio  ( latest stable ).
May I know your gradle version ?

I am using this library in [ESP RainMaker](https://github.com/espressif/esp-rainmaker-android) project.
Updated lib version to `implementation 'com.github.espressif:esp-idf-provisioning-android:lib-2.1.2'` locally.

Gradle version :
It is 7.4 in gradle-wraapper.properties

Android Studio : 
Android Studio Electric Eel | 2022.1.1
Build #AI-221.6008.13.2211.9477386, built on January 11, 2023

Also used Java version 11 for the project.

These configurations are working fine.
Can you check other configurations like gradle & java version ?
Meanwhile, I am also working on to remove jcenter or release jar.

Thanks.

**Comment by aa-v** [comment]
Hi @khushbushah2302 thank you very much! I am using 7.4 gradle, but nothing for the java version. Could you show your build.gradle please?

**Comment by aa-v** [comment]
Android Studio Electric Eel | 2022.1.1
Build #AI-221.6008.13.2211.9477386, built on January 11, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 amd64
Gradle 7.4

**Comment by aa-v** [comment]
` implementation 'com.github.espressif:esp-idf-provisioning-android:lib-2.0.13'` works fine

**Comment by aa-v** [comment]
I think we just need a more recent release.

**Comment by khushbushah2302** [comment]
As mentioned in above comment, I have tested with latest one. 
`implementation 'com.github.espressif:esp-idf-provisioning-android:lib-2.1.2'` is also working fine.

**Comment by aa-v** [comment]
Amazingly, since I was shipping a library not an app, I added the jitpack dependency to the example app's gradle and upgrade to 7.4 in the app and now it works fine. Thanks for all your help.
