### ISSUE TITLE
EspDevice.provision,  debug app no problem, but release app callback with createSessionFailed

### ISSUE THREAD

**Issue by Steven1937** [espressif/esp-idf-provisioning-android#93]
Hi,  EspDevice.provision(ssid, pwd, ProvisionListener),  debug app no problem, but release app callback with createSessionFailed: failed to create session

**Comment by KhushbuShah25** [comment]
Hi @Steven1937 , we have created a release build and uploaded that on PlayStore.
It is working fine. 
So trying to understand the difference of release build. Do you have minify flag enabled in your app?

**Comment by Steven1937** [comment]
Hi, yes, minifyEnabled for the release build,  but in  progaurd, I added " -keep class com.espressif.** {*; }",     EspDevice.connectToDevice()  no problem, but EspDevice.provision failed with initSession.  just the same step like the demo(scan QR code and then connect, and after EventBus received the connected callback , then call EspDevice.provission)

**Comment by Steven1937** [comment]
only difference from the demo is I removed the EspDevcie.scanNetwork  step.  diferectly go EspDevcice.provision to pair WiFi, debug build no problem , but release version failed with createSessionFailed

**Comment by Steven1937** [comment]
only difference from the demo is I removed the EspDevcie.scanNetwork step. dierectly call EspDevcice.provision to pair WiFi, debug build no problem , but release version failed with createSessionFailed

**Comment by Steven1937** [comment]
I confirmed if  don't minify , then release version also works fine,  but for the release version,  minify is required, so how to solve this? thanks

**Comment by Steven1937** [comment]
Thanks, i found the solutions, now no problem

**Comment by CrownedComedian** [comment]
@Steven1937 How did you resolve this issue?  I am facing a similar problem.

**Comment by CrownedComedian** [comment]
nvm, I was able to fix it after looking into #82 and discussing it with @KhushbuShah25 in #101

**Comment by gadget-man** [comment]
I don't think this issue should be closed - not having clarity in the instructions on what needs to be added to pro guard to allow the app to work properly has caused me a week of pain!
